// pois_db.js
// Base de datos de puntos de interés para RAIDIOAPP
// Provincias: Madrid, Toledo, Ciudad Real, Jaén, Granada
//
// ✅ Generado automáticamente desde Excel. NO EDITAR A MANO.
//    Fuente: pois.xlsx

export const POIS = [

  // =====================================================================
  // ================================ MADRID =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_mad_capital_madrid",
    nombre: "Madrid (capital de provincia)",
    lat: 40.416775,
    lng: -3.70379,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "datosCuriosos", "cultura"],
    tipo: "capital_provincia",
    radioActivacionMetros: 12000,

    perfil: "cultura",
    prioridad: 130,
    cooldownMin: 120,
    intereses: ["capitalidad", "historia_urbana", "monarquia", "cultura", "museos", "siglo_xvi_xvii"],
    sponsor: {
      "sponsorId": "bar_001",
      "sponsorNombre": "Bar Manolo",
      "mensaje": "Bocadillos y terraza y cocks",
      "url": "https://www.google.com/maps/place/Bernab%C3%A9u/@40.4544295,-3.6877974,17z/data=!3m1!5s0xd4228e2361e11b7:0x67f5c76cf9a0be21!4m6!3m5!1s0xd4228e23705d39f:0xa8fff6d26e2b1988!8m2!3d40.4530196!4d-3.6883748!16zL20vMDFneGx0?entry=ttu&g_ep=EgoyMDI2MDMyMi4wIKXMDSoASAFQAw%3D%3D"
    },
    eventos: [
      {
        "titulo": "id, titulo, descripcion, startDate, endDate, importancia"
      }
    ],
  },

  {
    id: "es_mad_guadarrama_parque_nacional",
    nombre: "Parque Nacional de la Sierra de Guadarrama",
    lat: 40.7849,
    lng: -3.9572,
    nivel: 1,
    categorias: ["naturaleza", "paisaje", "senderismo"],
    tipo: "parque_nacional",
    radioActivacionMetros: 12000,

    perfil: "naturaleza",
    prioridad: 115,
    cooldownMin: 45,
    intereses: ["senderismo", "cumbres", "miradores", "fauna", "flora", "clima", "paisaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_penalara",
    nombre: "Macizo de Peñalara",
    lat: 40.848,
    lng: -3.9642,
    nivel: 1,
    categorias: ["naturaleza", "montaña", "datosCuriosos"],
    tipo: "cumbre",
    radioActivacionMetros: 7500,

    perfil: "naturaleza",
    prioridad: 120,
    cooldownMin: 50,
    intereses: ["montañismo", "cumbre", "clima", "vistas", "glaciarismo", "senderos"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_pedriza",
    nombre: "La Pedriza (granito y escalada)",
    lat: 40.7313,
    lng: -3.8853,
    nivel: 2,
    categorias: ["naturaleza", "geologia", "paisaje"],
    tipo: "paraje_natural",
    radioActivacionMetros: 8000,

    perfil: "naturaleza",
    prioridad: 105,
    cooldownMin: 40,
    intereses: ["granito", "escalada", "bloques", "rutas", "vistas", "fauna", "flora", "seguridad_montana"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_lagunas_penalara",
    nombre: "Lagunas glaciares de Peñalara",
    lat: 40.8566,
    lng: -3.9578,
    nivel: 3,
    categorias: ["naturaleza", "geologia", "datosCuriosos"],
    tipo: "lagunas",
    radioActivacionMetros: 6000,

    perfil: "naturaleza",
    prioridad: 95,
    cooldownMin: 45,
    intereses: ["lagunas", "glaciarismo", "geologia", "ecosistemas", "fauna", "flora", "rutas"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_hayedo_montejo",
    nombre: "Hayedo de Montejo (UNESCO)",
    lat: 41.103323,
    lng: -3.489824,
    nivel: 1,
    categorias: ["naturaleza", "unesco", "paisaje"],
    tipo: "bosque",
    radioActivacionMetros: 4000,

    perfil: "naturaleza",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["bosque", "hayedo", "unesco", "biodiversidad", "otoño", "sendero"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_castillo_manzanares_real",
    nombre: "Castillo Nuevo de Manzanares el Real",
    lat: 40.727222,
    lng: -3.862222,
    nivel: 1,
    categorias: ["historia", "castillos", "arquitectura"],
    tipo: "castillo",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 120,
    cooldownMin: 45,
    intereses: ["castillo", "arquitectura", "edad_media", "linajes", "frontera", "visita"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_castillo_viejo_manzanares",
    nombre: "Castillo Viejo de Manzanares el Real",
    lat: 40.7319,
    lng: -3.8689,
    nivel: 3,
    categorias: ["historia", "castillos", "datosCuriosos"],
    tipo: "ruinas",
    radioActivacionMetros: 1500,

    perfil: "historia",
    prioridad: 80,
    cooldownMin: 30,
    intereses: ["ruinas", "castillo", "contexto_medieval", "paisaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_castillo_coracera",
    nombre: "Castillo de la Coracera (San Martín de Valdeiglesias)",
    lat: 40.3637,
    lng: -4.3972,
    nivel: 2,
    categorias: ["historia", "castillos", "pueblo"],
    tipo: "castillo",
    radioActivacionMetros: 3500,

    perfil: "historia",
    prioridad: 105,
    cooldownMin: 40,
    intereses: ["castillo", "señorios", "arquitectura", "pueblo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_castillo_buitrago",
    nombre: "Muralla y Castillo de Buitrago del Lozoya",
    lat: 40.9937,
    lng: -3.6369,
    nivel: 2,
    categorias: ["historia", "fortificaciones", "pueblo"],
    tipo: "muralla_castillo",
    radioActivacionMetros: 2500,

    perfil: "historia",
    prioridad: 110,
    cooldownMin: 40,
    intereses: ["muralla", "fortificacion", "edad_media", "río", "pueblo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_valle_caidos",
    nombre: "Valle de los Caídos",
    lat: 40.6419103,
    lng: -4.1508807,
    nivel: 1,
    categorias: ["historia", "guerra_civil", "memoria", "arquitectura", "datosCuriosos"],
    tipo: "memorial",
    radioActivacionMetros: 8000,

    perfil: "historia",
    prioridad: 125,
    cooldownMin: 90,
    intereses: ["arquitectura", "siglo_xx", "memoria_historica", "contexto_guerra_civil", "construccion"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_el_escorial",
    nombre: "Monasterio de San Lorenzo de El Escorial (UNESCO)",
    lat: 40.590105,
    lng: -4.147921,
    nivel: 1,
    categorias: ["historia", "monasterios", "unesco"],
    tipo: "monasterio",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 130,
    cooldownMin: 90,
    intereses: ["felipe_ii", "arquitectura", "religion", "arte", "monarquia", "unesco"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_aranjuez_palacio_jardines",
    nombre: "Palacio Real y Jardines de Aranjuez (UNESCO)",
    lat: 40.03101,
    lng: -3.60444,
    nivel: 1,
    categorias: ["historia", "paisaje", "unesco"],
    tipo: "palacio_jardines",
    radioActivacionMetros: 7000,

    perfil: "cultura",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["palacio", "jardines", "arte", "monarquia", "unesco", "paisaje_cultural"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_alcala_henares_centro",
    nombre: "Centro histórico de Alcalá de Henares (Cervantes)",
    lat: 40.481979,
    lng: -3.364135,
    nivel: 1,
    categorias: ["historia", "literatura", "unesco"],
    tipo: "casco_historico",
    radioActivacionMetros: 6000,

    perfil: "cultura",
    prioridad: 125,
    cooldownMin: 70,
    intereses: ["cervantes", "literatura", "universidad", "arquitectura", "unesco"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_universidad_alcala",
    nombre: "Universidad de Alcalá y Colegio Mayor de San Ildefonso",
    lat: 40.48293,
    lng: -3.36308,
    nivel: 2,
    categorias: ["historia", "arquitectura", "literatura"],
    tipo: "universidad_historica",
    radioActivacionMetros: 3500,

    perfil: "cultura",
    prioridad: 105,
    cooldownMin: 45,
    intereses: ["universidad", "arquitectura", "humanismo", "literatura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_puerto_somosierra_batalla",
    nombre: "Puerto de Somosierra (batalla de 1808)",
    lat: 41.1325,
    lng: -3.58167,
    nivel: 1,
    categorias: ["historia", "batallas", "datosCuriosos"],
    tipo: "paso_montana",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 140,
    cooldownMin: 80,
    intereses: ["guerra_independencia", "batalla", "paso_montana", "logistica", "terreno"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_brunete_batalla",
    nombre: "Brunete (Batalla de Brunete, 1937)",
    lat: 40.4059,
    lng: -3.9986,
    nivel: 2,
    categorias: ["historia", "batallas", "guerra_civil"],
    tipo: "pueblo_batalla",
    radioActivacionMetros: 4000,

    perfil: "historia",
    prioridad: 125,
    cooldownMin: 90,
    intereses: ["guerra_civil", "batalla", "frentes", "consecuencias"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_chinchon_plaza_mayor",
    nombre: "Chinchón y su Plaza Mayor",
    lat: 40.140267,
    lng: -3.422169,
    nivel: 2,
    categorias: ["historia", "cultura", "pueblo"],
    tipo: "pueblo",
    radioActivacionMetros: 8000,

    perfil: "parada",
    prioridad: 95,
    cooldownMin: 40,
    intereses: ["plaza_mayor", "gastronomia", "pueblo", "patrimonio", "plan_rapido"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_rascafria_paular",
    nombre: "Rascafría y Monasterio de El Paular",
    lat: 40.9044,
    lng: -3.8809,
    nivel: 2,
    categorias: ["historia", "monasterios", "naturaleza"],
    tipo: "pueblo_monasterio",
    radioActivacionMetros: 3000,

    perfil: "parada",
    prioridad: 105,
    cooldownMin: 45,
    intereses: ["monasterio", "valle", "rio", "senderismo", "pueblo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_patones_arriba",
    nombre: "Patones de Arriba (arquitectura negra)",
    lat: 40.8575,
    lng: -3.4852,
    nivel: 3,
    categorias: ["cultura", "arquitectura", "datosCuriosos"],
    tipo: "pueblo",
    radioActivacionMetros: 1800,

    perfil: "parada",
    prioridad: 80,
    cooldownMin: 35,
    intereses: ["arquitectura_negra", "pueblo", "paseo", "foto", "gastronomia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_nuevo_baztan",
    nombre: "Nuevo Baztán (villa barroca industrial)",
    lat: 40.3675,
    lng: -3.2427,
    nivel: 3,
    categorias: ["historia", "arquitectura", "datosCuriosos"],
    tipo: "conjunto_historico",
    radioActivacionMetros: 1800,

    perfil: "cultura",
    prioridad: 85,
    cooldownMin: 40,
    intereses: ["barroco", "industrializacion", "urbanismo", "arquitectura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_embalse_santillana",
    nombre: "Embalse de Santillana y Mirador",
    lat: 40.7194,
    lng: -3.8503,
    nivel: 3,
    categorias: ["naturaleza", "paisaje", "datosCuriosos"],
    tipo: "embalse",
    radioActivacionMetros: 6000,

    perfil: "naturaleza",
    prioridad: 80,
    cooldownMin: 35,
    intereses: ["embalse", "mirador", "foto", "aves", "paisaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_mad_las_presillas",
    nombre: "Área natural de Las Presillas (Lozoya)",
    lat: 40.8797,
    lng: -3.8852,
    nivel: 3,
    categorias: ["naturaleza", "rio", "paisaje"],
    tipo: "area_recreativa",
    radioActivacionMetros: 1500,

    perfil: "naturaleza",
    prioridad: 75,
    cooldownMin: 30,
    intereses: ["rio", "baño", "area_recreativa", "paseo", "familia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  // =====================================================================
  // ================================ TOLEDO =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_tol_capital_toledo",
    nombre: "Toledo (capital de provincia)",
    lat: 39.8568,
    lng: -4.0245,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "unesco", "cultura"],
    tipo: "capital_provincia",
    radioActivacionMetros: 10000,

    perfil: "cultura",
    prioridad: 135,
    cooldownMin: 120,
    intereses: ["unesco", "ciudad_historica", "tres_culturas", "arquitectura", "arte"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_toledo_ciudad_historica",
    nombre: "Casco histórico de Toledo (UNESCO)",
    lat: 39.8568,
    lng: -4.0245,
    nivel: 1,
    categorias: ["historia", "unesco", "arquitectura"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 8000,

    perfil: "cultura",
    prioridad: 140,
    cooldownMin: 90,
    intereses: ["unesco", "urbanismo", "arquitectura", "medieval", "visigodo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_alcazar_toledo",
    nombre: "Alcázar de Toledo",
    lat: 39.8573,
    lng: -4.0219,
    nivel: 1,
    categorias: ["historia", "guerra_civil", "arquitectura"],
    tipo: "fortaleza",
    radioActivacionMetros: 4500,

    perfil: "historia",
    prioridad: 135,
    cooldownMin: 90,
    intereses: ["fortaleza", "guerra_civil", "historia_militar", "arquitectura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_puente_alcantara",
    nombre: "Puente de Alcántara",
    lat: 39.85796,
    lng: -4.02062,
    nivel: 2,
    categorias: ["historia", "arquitectura"],
    tipo: "puente_romano",
    radioActivacionMetros: 3000,

    perfil: "historia",
    prioridad: 105,
    cooldownMin: 45,
    intereses: ["ingenieria", "romano", "rio", "arquitectura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_puente_san_martin",
    nombre: "Puente de San Martín",
    lat: 39.8589,
    lng: -4.0331,
    nivel: 2,
    categorias: ["historia", "arquitectura"],
    tipo: "puente_medieval",
    radioActivacionMetros: 2500,

    perfil: "historia",
    prioridad: 100,
    cooldownMin: 45,
    intereses: ["puente", "medieval", "rio", "arquitectura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_cerro_calderico_molinos",
    nombre: "Molinos de Consuegra (Cerro Calderico)",
    lat: 39.4579,
    lng: -3.6075,
    nivel: 1,
    categorias: ["historia", "literatura", "paisaje"],
    tipo: "molinos",
    radioActivacionMetros: 10500,

    perfil: "cultura",
    prioridad: 125,
    cooldownMin: 70,
    intereses: ["molinos", "quijote", "vistas", "paisaje", "viento"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_castillo_consuegra",
    nombre: "Castillo de Consuegra",
    lat: 39.4631,
    lng: -3.6084,
    nivel: 1,
    categorias: ["historia", "castillo"],
    tipo: "castillo",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["castillo", "ordenes_militares", "frontera", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_castillo_orgaz",
    nombre: "Castillo de Orgaz",
    lat: 39.6473,
    lng: -3.8751,
    nivel: 2,
    categorias: ["historia", "castillos"],
    tipo: "castillo",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 100,
    cooldownMin: 45,
    intereses: ["castillo", "edad_media", "señorio"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_castillo_escalona",
    nombre: "Castillo de Escalona",
    lat: 40.1677,
    lng: -4.4047,
    nivel: 2,
    categorias: ["historia", "castillos"],
    tipo: "castillo",
    radioActivacionMetros: 3000,

    perfil: "historia",
    prioridad: 105,
    cooldownMin: 45,
    intereses: ["castillo", "tajo", "frontera"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_malpica_castillo",
    nombre: "Castillo de Malpica de Tajo",
    lat: 39.8948,
    lng: -4.6561,
    nivel: 3,
    categorias: ["historia", "castillos"],
    tipo: "castillo",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 80,
    cooldownMin: 35,
    intereses: ["castillo", "tajo", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_torrejon_c_romana",
    nombre: "Villa romana de El Saucedo (Talavera la Nueva)",
    lat: 39.9667,
    lng: -5.0019,
    nivel: 3,
    categorias: ["historia", "romano"],
    tipo: "villa_romana",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 85,
    cooldownMin: 45,
    intereses: ["romano", "villa", "mosaicos", "vida_cotidiana"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_talavera_murallas",
    nombre: "Murallas y Torres de Talavera de la Reina",
    lat: 39.9614,
    lng: -4.8284,
    nivel: 2,
    categorias: ["historia", "arquitectura"],
    tipo: "muralla",
    radioActivacionMetros: 2500,

    perfil: "historia",
    prioridad: 95,
    cooldownMin: 45,
    intereses: ["muralla", "defensa", "arquitectura", "ciudad"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_basilica_prado",
    nombre: "Basílica del Prado (Talavera)",
    lat: 39.959,
    lng: -4.8241,
    nivel: 3,
    categorias: ["historia", "religion", "arte"],
    tipo: "basilica",
    radioActivacionMetros: 2000,

    perfil: "cultura",
    prioridad: 85,
    cooldownMin: 45,
    intereses: ["arte", "religion", "arquitectura", "devocion"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_belmonte_san_jose",
    nombre: "Castillo de San José (Belvís de la Jara)",
    lat: 39.7609,
    lng: -4.9463,
    nivel: 3,
    categorias: ["historia", "castillos"],
    tipo: "castillo",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 80,
    cooldownMin: 35,
    intereses: ["castillo", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_barrancas_burujon",
    nombre: "Las Barrancas de Burujón",
    lat: 39.8803,
    lng: -4.3497,
    nivel: 1,
    categorias: ["naturaleza", "paisaje", "geologia"],
    tipo: "barranco",
    radioActivacionMetros: 5000,

    perfil: "naturaleza",
    prioridad: 120,
    cooldownMin: 50,
    intereses: ["geologia", "miradores", "foto", "aves", "sendero_corto"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_santa_maria_melque",
    nombre: "Santa María de Melque",
    lat: 39.6744,
    lng: -4.2486,
    nivel: 2,
    categorias: ["historia", "visigodo"],
    tipo: "ermita",
    radioActivacionMetros: 2500,

    perfil: "historia",
    prioridad: 110,
    cooldownMin: 60,
    intereses: ["visigodo", "religion", "arte", "arquitectura"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_cuevas_huecas",
    nombre: "Cuevas y ermitas rupestres de Huecas",
    lat: 39.9701,
    lng: -4.1711,
    nivel: 3,
    categorias: ["historia", "arqueologia"],
    tipo: "cuevas",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 80,
    cooldownMin: 45,
    intereses: ["arqueologia", "rupestre", "cuevas", "religion"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_yebenes_cueva",
    nombre: "Cuevas del Chiquero (Los Yébenes)",
    lat: 39.5113,
    lng: -3.8952,
    nivel: 3,
    categorias: ["prehistoria", "arqueologia"],
    tipo: "cueva",
    radioActivacionMetros: 1500,

    perfil: "historia",
    prioridad: 75,
    cooldownMin: 45,
    intereses: ["prehistoria", "cuevas", "arqueologia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_castillo_dos_hermanas",
    nombre: "Castillo de Dos Hermanas (Navahermosa)",
    lat: 39.5985,
    lng: -4.5763,
    nivel: 3,
    categorias: ["historia", "castillos"],
    tipo: "castillo",
    radioActivacionMetros: 2000,

    perfil: "historia",
    prioridad: 80,
    cooldownMin: 35,
    intereses: ["castillo", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_montes_toledo",
    nombre: "Montes de Toledo (Puerto del Milagro)",
    lat: 39.5127,
    lng: -4.3216,
    nivel: 2,
    categorias: ["naturaleza", "paisaje"],
    tipo: "montana",
    radioActivacionMetros: 4500,

    perfil: "naturaleza",
    prioridad: 105,
    cooldownMin: 45,
    intereses: ["paisaje", "sierra", "fauna", "senderismo", "miradores"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_tol_camunas_tamborada",
    nombre: "Museo del Pecado Mortal (Camuñas)",
    lat: 39.4326,
    lng: -3.4551,
    nivel: 3,
    categorias: ["cultura", "tradicion", "curiosidades"],
    tipo: "museo",
    radioActivacionMetros: 1500,

    perfil: "cultura",
    prioridad: 75,
    cooldownMin: 45,
    intereses: ["tradiciones", "museo", "curiosidades", "cultura_local"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  // =====================================================================
  // ================================ CIUDAD REAL =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_cr_capital_ciudad_real",
    nombre: "Ciudad Real (capital de provincia)",
    lat: 38.9848,
    lng: -3.927,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "cultura", "datosCuriosos"],
    tipo: "capital_provincia",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 125,
    cooldownMin: 120,
    intereses: ["capitalidad", "historia_urbana", "cultura", "mancha"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_almagro_plaza_mayor",
    nombre: "Almagro y su Plaza Mayor / Corral de Comedias",
    lat: 38.8894,
    lng: -3.7068,
    nivel: 1,
    categorias: ["historia", "teatro", "arquitectura", "pueblo"],
    tipo: "pueblo_historico",
    radioActivacionMetros: 6000,

    perfil: "parada",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["teatro", "corral_de_comedias", "arquitectura", "pueblo", "plan_cultural"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_tablas_daimiel",
    nombre: "Parque Nacional de Las Tablas de Daimiel",
    lat: 39.1451,
    lng: -3.687,
    nivel: 1,
    categorias: ["naturaleza", "aves", "humedal", "unesco"],
    tipo: "parque_nacional",
    radioActivacionMetros: 8000,

    perfil: "naturaleza",
    prioridad: 125,
    cooldownMin: 60,
    intereses: ["humedal", "aves", "observacion", "sendero", "ecosistema"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_calatrava_nueva",
    nombre: "Castillo de Calatrava la Nueva",
    lat: 38.7956,
    lng: -3.8236,
    nivel: 2,
    categorias: ["historia", "castillos", "ordenes_militares"],
    tipo: "castillo",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["ordenes_militares", "castillo", "defensa", "reconquista"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_valdepenas_vino",
    nombre: "Valdepeñas (tierra de vino y batallas napoleónicas)",
    lat: 38.7621,
    lng: -3.3843,
    nivel: 2,
    categorias: ["historia", "vino", "cultura", "datosCuriosos"],
    tipo: "ciudad",
    radioActivacionMetros: 7000,

    perfil: "parada",
    prioridad: 105,
    cooldownMin: 50,
    intereses: ["vino", "cultura_local", "gastronomia", "historia_napoleonica"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_puertollano_mineria",
    nombre: "Puertollano (minería e industria histórica)",
    lat: 38.6879,
    lng: -4.1123,
    nivel: 3,
    categorias: ["historia", "industria", "datosCuriosos"],
    tipo: "ciudad_industrial",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 85,
    cooldownMin: 60,
    intereses: ["industria", "mineria", "historia_economica", "siglo_xix_xx"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_viso_marques_santa_cruz",
    nombre: "Palacio del Marqués de Santa Cruz (Viso del Marqués)",
    lat: 38.523,
    lng: -3.5619,
    nivel: 3,
    categorias: ["historia", "arquitectura", "renacimiento"],
    tipo: "palacio",
    radioActivacionMetros: 4000,

    perfil: "cultura",
    prioridad: 90,
    cooldownMin: 60,
    intereses: ["renacimiento", "arte", "arquitectura", "palacio"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_lagunas_ruidera",
    nombre: "Parque Natural de las Lagunas de Ruidera",
    lat: 38.951,
    lng: -2.89,
    nivel: 2,
    categorias: ["naturaleza", "paisaje", "agua"],
    tipo: "parque_natural",
    radioActivacionMetros: 9000,

    perfil: "naturaleza",
    prioridad: 115,
    cooldownMin: 60,
    intereses: ["lagunas", "agua", "rutas", "baño", "fauna", "paisaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_manzanares_ciudad",
    nombre: "Manzanares (cruce histórico de la A4)",
    lat: 38.9993,
    lng: -3.3694,
    nivel: 2,
    categorias: ["historia", "mancha", "datosCuriosos"],
    tipo: "ciudad",
    radioActivacionMetros: 7000,

    perfil: "cultura",
    prioridad: 95,
    cooldownMin: 60,
    intereses: ["mancha", "rutas", "comunicaciones", "historia_local"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_puerto_lapice_venta",
    nombre: "Puerto Lápice (ventas cervantinas y paso de la A4)",
    lat: 39.3244,
    lng: -3.4827,
    nivel: 2,
    categorias: ["historia", "cervantes", "pueblo", "datosCuriosos"],
    tipo: "pueblo_historico",
    radioActivacionMetros: 6000,

    perfil: "parada",
    prioridad: 110,
    cooldownMin: 60,
    intereses: ["quijote", "ventas", "cervantes", "pueblo", "parada_viaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_villanueva_infantes",
    nombre: "Villanueva de los Infantes (corazón histórico de La Mancha)",
    lat: 38.7373,
    lng: -3.0132,
    nivel: 2,
    categorias: ["historia", "pueblo", "cultura"],
    tipo: "pueblo_historico",
    radioActivacionMetros: 6000,

    perfil: "parada",
    prioridad: 100,
    cooldownMin: 60,
    intereses: ["pueblo", "patrimonio", "mancha", "plan_paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_motilla_azuer",
    nombre: "Motilla del Azuer (prehistoria en La Mancha)",
    lat: 39.034,
    lng: -3.5111,
    nivel: 3,
    categorias: ["prehistoria", "arqueologia", "datosCuriosos"],
    tipo: "yacimiento",
    radioActivacionMetros: 4000,

    perfil: "historia",
    prioridad: 90,
    cooldownMin: 90,
    intereses: ["prehistoria", "arqueologia", "yacimiento", "agua", "ingenieria_antigua"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_castillo_dona_berenguela",
    nombre: "Castillo de Doña Berenguela (Bolaños de Calatrava)",
    lat: 38.9063,
    lng: -3.6675,
    nivel: 3,
    categorias: ["historia", "castillos", "ordenes_militares"],
    tipo: "castillo",
    radioActivacionMetros: 4000,

    perfil: "historia",
    prioridad: 85,
    cooldownMin: 60,
    intereses: ["castillo", "ordenes_militares", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_parque_cabaneros",
    nombre: "Parque Nacional de Cabañeros (acceso sur)",
    lat: 39.3087,
    lng: -4.4571,
    nivel: 1,
    categorias: ["naturaleza", "fauna", "parque_nacional"],
    tipo: "parque_nacional",
    radioActivacionMetros: 12000,

    perfil: "naturaleza",
    prioridad: 125,
    cooldownMin: 60,
    intereses: ["fauna", "berrea", "observacion", "paisaje", "senderismo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_campo_calatrava_volcanes",
    nombre: "Campo de Calatrava (zona volcánica y maares)",
    lat: 38.946,
    lng: -3.9,
    nivel: 2,
    categorias: ["geologia", "naturaleza", "datosCuriosos"],
    tipo: "paisaje_volcanico",
    radioActivacionMetros: 9000,

    perfil: "naturaleza",
    prioridad: 120,
    cooldownMin: 60,
    intereses: ["geologia", "volcanes", "maares", "paisaje", "rocas"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_cr_orden_calatrava_contexto",
    nombre: "Orden de Calatrava (historia militar de la zona)",
    lat: 38.8894,
    lng: -3.7068,
    nivel: 3,
    categorias: ["historia", "ordenes_militares", "datosCuriosos"],
    tipo: "contexto_historico",
    radioActivacionMetros: 8000,

    perfil: "historia",
    prioridad: 95,
    cooldownMin: 90,
    intereses: ["ordenes_militares", "reconquista", "frontera", "contexto"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  // =====================================================================
  // ================================ JAÉN =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_ja_capital_jaen",
    nombre: "Jaén (capital de provincia)",
    lat: 37.7796,
    lng: -3.7849,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "cultura", "aceite"],
    tipo: "capital_provincia",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 125,
    cooldownMin: 120,
    intereses: ["aceite", "cultura", "historia_urbana", "capitalidad"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_despenaperros",
    nombre: "Parque Natural de Despeñaperros (puerta de Andalucía)",
    lat: 38.399,
    lng: -3.49,
    nivel: 1,
    categorias: ["naturaleza", "geologia", "paisaje", "historia"],
    tipo: "parque_natural",
    radioActivacionMetros: 9000,

    perfil: "naturaleza",
    prioridad: 130,
    cooldownMin: 60,
    intereses: ["geologia", "desfiladero", "paisaje", "paso_natural", "fauna", "rutas"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_bailen_batalla",
    nombre: "Bailén (batalla de 1808 contra Napoleón)",
    lat: 38.0962,
    lng: -3.775,
    nivel: 1,
    categorias: ["historia", "batallas", "datosCuriosos"],
    tipo: "ciudad_batalla",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 150,
    cooldownMin: 120,
    intereses: ["guerra_independencia", "batalla", "consecuencias", "logistica"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_linares_minas",
    nombre: "Linares (minería histórica y patrimonio industrial)",
    lat: 38.095,
    lng: -3.636,
    nivel: 2,
    categorias: ["historia", "industria", "mineria", "datosCuriosos"],
    tipo: "ciudad_industrial",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 100,
    cooldownMin: 90,
    intereses: ["mineria", "industria", "patrimonio", "siglo_xix_xx"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_castillo_santa_catalina",
    nombre: "Castillo de Santa Catalina (Jaén)",
    lat: 37.7654,
    lng: -3.7922,
    nivel: 2,
    categorias: ["historia", "castillos", "mirador"],
    tipo: "castillo",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 115,
    cooldownMin: 60,
    intereses: ["castillo", "mirador", "frontera", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_ubeda_renacimiento",
    nombre: "Úbeda (Renacimiento, UNESCO)",
    lat: 38.011,
    lng: -3.371,
    nivel: 1,
    categorias: ["historia", "unesco", "arquitectura", "renacimiento"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 140,
    cooldownMin: 120,
    intereses: ["renacimiento", "unesco", "arquitectura", "arte", "urbanismo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_baeza_renacimiento",
    nombre: "Baeza (Renacimiento, UNESCO)",
    lat: 37.993,
    lng: -3.4689,
    nivel: 1,
    categorias: ["historia", "unesco", "arquitectura", "renacimiento"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 140,
    cooldownMin: 120,
    intereses: ["renacimiento", "unesco", "arquitectura", "arte", "historia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_navas_tolosa_batalla",
    nombre: "Las Navas de Tolosa (batalla de 1212)",
    lat: 38.3053,
    lng: -3.3437,
    nivel: 1,
    categorias: ["historia", "batallas", "reconquista", "datosCuriosos"],
    tipo: "campo_batalla",
    radioActivacionMetros: 8000,

    perfil: "historia",
    prioridad: 160,
    cooldownMin: 180,
    intereses: ["reconquista", "batalla", "terreno", "logistica", "consecuencias"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_banos_encina_castillo",
    nombre: "Baños de la Encina y Castillo de Burgalimar",
    lat: 38.1735,
    lng: -3.7746,
    nivel: 2,
    categorias: ["historia", "castillos", "pueblo"],
    tipo: "castillo",
    radioActivacionMetros: 6000,

    perfil: "parada",
    prioridad: 120,
    cooldownMin: 90,
    intereses: ["castillo", "pueblo", "edad_media", "plan_visita"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_carolina_nuevas_poblaciones",
    nombre: "La Carolina (Nuevas Poblaciones de Sierra Morena)",
    lat: 38.2752,
    lng: -3.6178,
    nivel: 2,
    categorias: ["historia", "ilustracion", "datosCuriosos"],
    tipo: "ciudad",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["ilustracion", "poblamiento", "reformas", "siglo_xviii"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_andujar_santuario_cabeza",
    nombre: "Andújar y Santuario de la Virgen de la Cabeza",
    lat: 38.039,
    lng: -4.054,
    nivel: 3,
    categorias: ["historia", "religion", "naturaleza"],
    tipo: "santuario",
    radioActivacionMetros: 8000,

    perfil: "parada",
    prioridad: 95,
    cooldownMin: 90,
    intereses: ["religion", "santuario", "paisaje", "romeria", "rutas"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_cazorla_parque_natural",
    nombre: "Parque Natural Sierras de Cazorla, Segura y Las Villas",
    lat: 37.91,
    lng: -2.93,
    nivel: 1,
    categorias: ["naturaleza", "paisaje", "fauna", "parque_natural"],
    tipo: "parque_natural",
    radioActivacionMetros: 15000,

    perfil: "naturaleza",
    prioridad: 130,
    cooldownMin: 90,
    intereses: ["fauna", "senderismo", "ríos", "bosques", "miradores", "naturaleza"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_arjona_historia_almohade",
    nombre: "Arjona (orígenes íberos y época almohade)",
    lat: 37.9355,
    lng: -4.0552,
    nivel: 3,
    categorias: ["historia", "arqueologia", "datosCuriosos"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 6000,

    perfil: "historia",
    prioridad: 95,
    cooldownMin: 120,
    intereses: ["iberos", "andalusi", "arqueologia", "contexto"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_martos_pena",
    nombre: "Martos y la Peña (torreones y frontera medieval)",
    lat: 37.721,
    lng: -3.967,
    nivel: 2,
    categorias: ["historia", "castillos", "paisaje"],
    tipo: "ciudad_mirador",
    radioActivacionMetros: 7000,

    perfil: "parada",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["mirador", "frontera_medieval", "paisaje", "castillos"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_ja_mar_de_olivos",
    nombre: "Mar de olivos (paisaje del aceite de Jaén)",
    lat: 38,
    lng: -3.8,
    nivel: 3,
    categorias: ["paisaje", "datosCuriosos", "cultura", "aceite"],
    tipo: "paisaje_cultural",
    radioActivacionMetros: 12000,

    perfil: "cultura",
    prioridad: 85,
    cooldownMin: 90,
    intereses: ["aceite", "paisaje", "agricultura", "cultura_local"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  // =====================================================================
  // ================================ GRANADA =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_gr_capital_granada",
    nombre: "Granada (capital de provincia)",
    lat: 37.1773,
    lng: -3.5986,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "cultura", "datosCuriosos"],
    tipo: "capital_provincia",
    radioActivacionMetros: 11000,

    perfil: "cultura",
    prioridad: 130,
    cooldownMin: 120,
    intereses: ["reino_nazari", "renacimiento", "cultura", "historia_urbana"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_alhambra",
    nombre: "La Alhambra y Generalife",
    lat: 37.1761,
    lng: -3.5881,
    nivel: 1,
    categorias: ["historia", "unesco", "arquitectura", "andalusi"],
    tipo: "monumento_unesco",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 170,
    cooldownMin: 180,
    intereses: ["andalusi", "arquitectura", "arte", "unesco", "reino_nazari"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_albaicin_san_nicolas",
    nombre: "Albaicín y Mirador de San Nicolás",
    lat: 37.1806,
    lng: -3.594,
    nivel: 2,
    categorias: ["historia", "paisaje", "barrio_historico"],
    tipo: "barrio_mirador",
    radioActivacionMetros: 5000,

    perfil: "parada",
    prioridad: 130,
    cooldownMin: 90,
    intereses: ["mirador", "barrio_historico", "paisaje", "foto", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_sierra_nevada",
    nombre: "Sierra Nevada (acceso Pradollano)",
    lat: 37.095,
    lng: -3.394,
    nivel: 1,
    categorias: ["naturaleza", "montaña", "paisaje", "datosCuriosos"],
    tipo: "parque_natural",
    radioActivacionMetros: 12000,

    perfil: "naturaleza",
    prioridad: 140,
    cooldownMin: 90,
    intereses: ["montaña", "senderismo", "nieve", "vistas", "fauna", "altitud"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_loja_paso_historico",
    nombre: "Loja (puerta occidental de Granada)",
    lat: 37.168,
    lng: -4.151,
    nivel: 3,
    categorias: ["historia", "ciudad", "datosCuriosos"],
    tipo: "ciudad",
    radioActivacionMetros: 6000,

    perfil: "historia",
    prioridad: 90,
    cooldownMin: 90,
    intereses: ["frontera", "reconquista", "ruta", "ciudad"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_guadix_cuevas",
    nombre: "Guadix (catedral y cuevas habitadas)",
    lat: 37.3,
    lng: -3.134,
    nivel: 2,
    categorias: ["historia", "arquitectura", "datosCuriosos"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 8000,

    perfil: "parada",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["cuevas", "arquitectura", "catedral", "plan_visita"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_catedral_capilla_real",
    nombre: "Catedral y Capilla Real (Reyes Católicos)",
    lat: 37.1764,
    lng: -3.5995,
    nivel: 1,
    categorias: ["historia", "arquitectura", "reyes_catolicos"],
    tipo: "catedral",
    radioActivacionMetros: 6000,

    perfil: "historia",
    prioridad: 160,
    cooldownMin: 180,
    intereses: ["reyes_catolicos", "religion", "arte", "arquitectura", "renacimiento"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_sacromonte_cuevas",
    nombre: "Sacromonte (cuevas y cultura gitana)",
    lat: 37.1835,
    lng: -3.5858,
    nivel: 2,
    categorias: ["historia", "cultura", "datosCuriosos"],
    tipo: "barrio_historico",
    radioActivacionMetros: 6000,

    perfil: "cultura",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["cuevas", "cultura_git", "tradiciones", "barrio"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_velez_benaudalla_valle",
    nombre: "Vélez de Benaudalla (valle camino de la costa)",
    lat: 36.8338,
    lng: -3.5169,
    nivel: 3,
    categorias: ["paisaje", "pueblo", "datosCuriosos"],
    tipo: "pueblo_valle",
    radioActivacionMetros: 7000,

    perfil: "parada",
    prioridad: 85,
    cooldownMin: 60,
    intereses: ["valle", "paisaje", "pueblo", "parada_viaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_moclin_castillo",
    nombre: "Moclín (castillo de frontera nazarí)",
    lat: 37.3423,
    lng: -3.7861,
    nivel: 3,
    categorias: ["historia", "castillos", "frontera_nazari"],
    tipo: "castillo",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 95,
    cooldownMin: 90,
    intereses: ["frontera_nazari", "castillo", "vigilancia", "edad_media"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_alpujarras_lanjaron",
    nombre: "Las Alpujarras y Lanjarón (paisaje morisco)",
    lat: 36.9194,
    lng: -3.4802,
    nivel: 2,
    categorias: ["historia", "paisaje", "naturaleza"],
    tipo: "comarca",
    radioActivacionMetros: 12000,

    perfil: "parada",
    prioridad: 120,
    cooldownMin: 90,
    intereses: ["paisaje", "rutas", "pueblos", "agua", "historia_morisca"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_fuente_vaqueros_lorca",
    nombre: "Fuente Vaqueros (cuna de Federico García Lorca)",
    lat: 37.2199,
    lng: -3.7856,
    nivel: 3,
    categorias: ["historia", "literatura", "datosCuriosos"],
    tipo: "pueblo",
    radioActivacionMetros: 6000,

    perfil: "cultura",
    prioridad: 90,
    cooldownMin: 90,
    intereses: ["lorca", "literatura", "cultura", "pueblo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_suspiro_moro",
    nombre: "Puerto del Suspiro del Moro (última mirada de Boabdil)",
    lat: 37.0151,
    lng: -3.6005,
    nivel: 2,
    categorias: ["historia", "reconquista", "paisaje"],
    tipo: "puerto_montana",
    radioActivacionMetros: 9000,

    perfil: "historia",
    prioridad: 135,
    cooldownMin: 120,
    intereses: ["reconquista", "boabdil", "paso_montana", "paisaje", "cronica"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gr_reino_nazari_contexto",
    nombre: "Reino Nazarí de Granada (contexto histórico)",
    lat: 37.1773,
    lng: -3.5986,
    nivel: 3,
    categorias: ["historia", "andalusi", "datosCuriosos"],
    tipo: "contexto_historico",
    radioActivacionMetros: 10000,

    perfil: "historia",
    prioridad: 95,
    cooldownMin: 180,
    intereses: ["andalusi", "contexto", "reino_nazari", "sociedad", "economia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  // =====================================================================
  // ================================ OTROS =============================
  // =====================================================================

  // ✅ CAPITAL
  {
    id: "es_gua_capital_guadalajara",
    nombre: "Guadalajara (capital de provincia)",
    lat: 40.63333,
    lng: -3.16667,
    nivel: 1,
    categorias: ["historia", "provincia", "capital", "cultura", "datosCuriosos"],
    tipo: "capital_provincia",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 125,
    cooldownMin: 120,
    intereses: ["historia_urbana", "patrimonio", "rio_henares", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_palacio_infantado",
    nombre: "Palacio del Infantado (Guadalajara)",
    lat: 40.6314256,
    lng: -3.1650391,
    nivel: 1,
    categorias: ["historia", "arquitectura", "cultura", "datosCuriosos"],
    tipo: "palacio",
    radioActivacionMetros: 5000,

    perfil: "historia",
    prioridad: 130,
    cooldownMin: 120,
    intereses: ["arquitectura", "gótico_isabelino", "renacimiento", "nobles"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_concatedral_santa_maria",
    nombre: "Concatedral de Santa María (Guadalajara)",
    lat: 40.6345712,
    lng: -3.1652753,
    nivel: 2,
    categorias: ["historia", "arquitectura", "religion", "arte"],
    tipo: "iglesia",
    radioActivacionMetros: 4000,

    perfil: "cultura",
    prioridad: 95,
    cooldownMin: 90,
    intereses: ["arte", "arquitectura", "religion", "centro_historico"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_castillo_torija",
    nombre: "Castillo de Torija (cerca de la A2)",
    lat: 40.7431409,
    lng: -3.0341528,
    nivel: 2,
    categorias: ["historia", "castillos", "arquitectura", "datosCuriosos"],
    tipo: "castillo",
    radioActivacionMetros: 3000,

    perfil: "historia",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["castillo", "edad_media", "frontera", "museo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_brihuega_jardines",
    nombre: "Brihuega (jardines y casco histórico)",
    lat: 40.7597,
    lng: -2.8705,
    nivel: 2,
    categorias: ["historia", "cultura", "pueblo", "paisaje", "datosCuriosos"],
    tipo: "pueblo",
    radioActivacionMetros: 11000,

    perfil: "parada",
    prioridad: 100,
    cooldownMin: 90,
    intereses: ["pueblo", "jardines", "historia_local", "foto", "parada_viaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_pastrana_ducal",
    nombre: "Pastrana (palacio ducal y villa histórica)",
    lat: 40.417,
    lng: -2.922,
    nivel: 3,
    categorias: ["historia", "pueblo", "arquitectura", "cultura"],
    tipo: "pueblo_historico",
    radioActivacionMetros: 12000,

    perfil: "parada",
    prioridad: 85,
    cooldownMin: 120,
    intereses: ["palacio_ducal", "princesa_de_eboli", "historia_moderna", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_siguenca_casco",
    nombre: "Sigüenza (casco medieval)",
    lat: 41.0666189,
    lng: -2.6524928,
    nivel: 1,
    categorias: ["historia", "catedral\" \"pueblo", "arquitectura", "cultura", "datosCuriosos"],
    tipo: "casco_historico",
    radioActivacionMetros: 11000,

    perfil: "cultura",
    prioridad: 140,
    cooldownMin: 150,
    intereses: ["medieval", "catedral", "castillo_parador", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_salinas_imon",
    nombre: "Salinas de Imón (patrimonio salinero)",
    lat: 41.1600875,
    lng: -2.7391867,
    nivel: 3,
    categorias: ["historia", "industria", "datosCuriosos", "patrimonio"],
    tipo: "salinas",
    radioActivacionMetros: 3000,

    perfil: "cultura",
    prioridad: 80,
    cooldownMin: 120,
    intereses: ["sal", "industria_historica", "patrimonio", "paisaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_barranco_rio_dulce",
    nombre: "Parque Natural del Barranco del Río Dulce",
    lat: 41.0205072,
    lng: -2.5917397,
    nivel: 1,
    categorias: ["naturaleza", "paisaje", "geologia", "senderismo", "aves"],
    tipo: "parque_natural",
    radioActivacionMetros: 9000,

    perfil: "naturaleza",
    prioridad: 130,
    cooldownMin: 90,
    intereses: ["senderismo", "cañón", "aves", "miradores", "geologia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_pelegrina_mirador",
    nombre: "Mirador de Pelegrina (Río Dulce)",
    lat: 41.0148481,
    lng: -2.6333063,
    nivel: 2,
    categorias: ["naturaleza", "paisaje", "mirador", "senderismo"],
    tipo: "mirador",
    radioActivacionMetros: 6000,

    perfil: "naturaleza",
    prioridad: 110,
    cooldownMin: 90,
    intereses: ["mirador", "sendero", "foto", "cañon"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_gua_alcolea_pinar_nudo",
    nombre: "Alcolea del Pinar (nudo A2 / N-211)",
    lat: 41.0355,
    lng: -2.467,
    nivel: 3,
    categorias: ["cultura", "carretera", "datosCuriosos"],
    tipo: "pueblo",
    radioActivacionMetros: 5000,

    perfil: "parada",
    prioridad: 75,
    cooldownMin: 90,
    intereses: ["parada_viaje", "servicios", "nudo_carreteras"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_sor_medinaceli_villa",
    nombre: "Medinaceli (villa histórica)",
    lat: 41.1720815,
    lng: -2.4360339,
    nivel: 1,
    categorias: ["historia", "cultura", "arquitectura", "datosCuriosos"],
    tipo: "villa_historica",
    radioActivacionMetros: 3000,

    perfil: "cultura",
    prioridad: 145,
    cooldownMin: 180,
    intereses: ["romano", "medieval", "miradores", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_sor_arco_romano_medinaceli",
    nombre: "Arco Romano de Medinaceli",
    lat: 41.1707542,
    lng: -2.4350253,
    nivel: 1,
    categorias: ["historia", "romano", "arquitectura"],
    tipo: "monumento_romano",
    radioActivacionMetros: 1500,

    perfil: "historia",
    prioridad: 155,
    cooldownMin: 240,
    intereses: ["romano", "ingenieria", "via_romana", "patrimonio"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_sor_monasterio_huerta",
    nombre: "Monasterio de Santa María de Huerta",
    lat: 41.2615311,
    lng: -2.1794545,
    nivel: 1,
    categorias: ["historia", "monasterios", "arquitectura", "religion"],
    tipo: "monasterio",
    radioActivacionMetros: 4000,

    perfil: "historia",
    prioridad: 150,
    cooldownMin: 180,
    intereses: ["cister", "arte", "arquitectura", "religion"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_sor_arcos_jalon",
    nombre: "Arcos de Jalón (valle y paso histórico)",
    lat: 41.2149,
    lng: -2.2717,
    nivel: 3,
    categorias: ["historia", "pueblo", "datosCuriosos"],
    tipo: "pueblo",
    radioActivacionMetros: 1000,

    perfil: "parada",
    prioridad: 80,
    cooldownMin: 90,
    intereses: ["valle_jalon", "parada_viaje", "historia_local"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_sor_embalse_monteagudo",
    nombre: "Embalse de Monteagudo de las Vicarías",
    lat: 41.365,
    lng: -2.17,
    nivel: 2,
    categorias: ["naturaleza", "aves", "humedal", "paisaje"],
    tipo: "embalse",
    radioActivacionMetros: 11000,

    perfil: "naturaleza",
    prioridad: 105,
    cooldownMin: 90,
    intereses: ["aves", "observacion", "paisaje", "foto"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_alhama_aragon",
    nombre: "Alhama de Aragón (balnearios y casco)",
    lat: 41.2967,
    lng: -1.8942,
    nivel: 2,
    categorias: ["cultura", "aguas_termales", "parada", "datosCuriosos"],
    tipo: "balneario",
    radioActivacionMetros: 2000,

    perfil: "parada",
    prioridad: 110,
    cooldownMin: 120,
    intereses: ["balneario", "aguas_termales", "descanso", "parada_viaje"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_lago_termal_alhama",
    nombre: "Lago Termal de Alhama de Aragón",
    lat: 41.2948505,
    lng: -1.9000086,
    nivel: 2,
    categorias: ["naturaleza", "agua", "datosCuriosos"],
    tipo: "lago_termal",
    radioActivacionMetros: 2000,

    perfil: "naturaleza",
    prioridad: 95,
    cooldownMin: 120,
    intereses: ["aguas_termales", "baño", "paisaje", "relax"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_ateca",
    nombre: "Ateca (casco histórico)",
    lat: 41.3293183,
    lng: -1.7997732,
    nivel: 3,
    categorias: ["historia", "pueblo", "cultura"],
    tipo: "pueblo",
    radioActivacionMetros: 7000,

    perfil: "parada",
    prioridad: 80,
    cooldownMin: 90,
    intereses: ["pueblo", "parada_viaje", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_calatayud",
    nombre: "Calatayud (mudéjar y casco histórico)",
    lat: 41.354,
    lng: -1.6426,
    nivel: 1,
    categorias: ["historia", "cultura", "mudejar", "datosCuriosos"],
    tipo: "ciudad_historica",
    radioActivacionMetros: 9000,

    perfil: "cultura",
    prioridad: 145,
    cooldownMin: 150,
    intereses: ["mudejar", "casco_historico", "arquitectura", "paseo"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_colegiata_santa_maria",
    nombre: "Colegiata de Santa María la Mayor (Calatayud, mudéjar)",
    lat: 41.3538,
    lng: -1.6465,
    nivel: 1,
    categorias: ["historia", "mudejar", "arquitectura", "religion", "arte"],
    tipo: "iglesia_mudejar",
    radioActivacionMetros: 6000,

    perfil: "historia",
    prioridad: 155,
    cooldownMin: 180,
    intereses: ["mudejar", "arte", "arquitectura", "religion"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_castillo_ayub",
    nombre: "Castillo de Ayub (Calatayud)",
    lat: 41.352,
    lng: -1.64,
    nivel: 2,
    categorias: ["historia", "castillos", "mirador"],
    tipo: "castillo",
    radioActivacionMetros: 7000,

    perfil: "historia",
    prioridad: 130,
    cooldownMin: 150,
    intereses: ["castillo", "mirador", "frontera", "medieval"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_embalse_tranquera",
    nombre: "Embalse de La Tranquera (cerca de Nuévalos)",
    lat: 41.236636,
    lng: -1.8383977,
    nivel: 2,
    categorias: ["naturaleza", "paisaje", "agua", "datosCuriosos"],
    tipo: "embalse",
    radioActivacionMetros: 7000,

    perfil: "naturaleza",
    prioridad: 120,
    cooldownMin: 90,
    intereses: ["embalse", "paisaje", "foto", "agua"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_nuevalos",
    nombre: "Nuévalos (pueblo de acceso al Monasterio de Piedra)",
    lat: 41.212,
    lng: -1.789,
    nivel: 3,
    categorias: ["pueblo", "parada", "cultura"],
    tipo: "pueblo",
    radioActivacionMetros: 5000,

    perfil: "parada",
    prioridad: 95,
    cooldownMin: 90,
    intereses: ["parada_viaje", "pueblo", "acceso"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_monasterio_piedra",
    nombre: "Monasterio de Piedra (Nuévalos)",
    lat: 41.1932396,
    lng: -1.7851055,
    nivel: 1,
    categorias: ["historia", "monasterios", "naturaleza", "paisaje", "datosCuriosos"],
    tipo: "monasterio_parque",
    radioActivacionMetros: 3000,

    perfil: "historia",
    prioridad: 170,
    cooldownMin: 240,
    intereses: ["cister", "Desamortizción de Mendizábal", "Don Pablo Muntadas Campeny", "cascadas", "jardines", "paseo", "fotografia"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_jaraba_cascadas",
    nombre: "Jaraba (cascadas y barrancos)",
    lat: 41.1904357,
    lng: -1.8872258,
    nivel: 2,
    categorias: ["naturaleza", "paisaje", "senderismo", "agua"],
    tipo: "cascadas",
    radioActivacionMetros: 3000,

    perfil: "naturaleza",
    prioridad: 125,
    cooldownMin: 120,
    intereses: ["cascadas", "senderismo", "barranco", "agua"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

  {
    id: "es_zar_daroca_murallas",
    nombre: "Daroca (murallas y ciudad medieval)",
    lat: 41.1151,
    lng: -1.4146,
    nivel: 2,
    categorias: ["historia", "ciudad_medieval", "arquitectura", "cultura"],
    tipo: "ciudad_medieval",
    radioActivacionMetros: 1000,

    perfil: "cultura",
    prioridad: 120,
    cooldownMin: 150,
    intereses: ["murallas", "medieval", "paseo", "patrimonio"],
    // sponsor: { sponsorId, sponsorNombre, mensaje, url },
    // eventos: [{ id, titulo, descripcion, startDate, endDate, importancia }],
  },

];
